server:
  port: 2020
spring:
  application:
    name: bws_blog
  datasource:
    url:  jdbc:mysql://localhost:3306/bws_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
